config/routes.rb
CookBook::Application.routes.draw do
  resources :books, :recipes, :ingredients, :users, :sessions

  root to: 'books#index'

  get '/signup' => 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get'/signin' => 'sessions#new'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, :ingredient_ids
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.create(params[:book])
    render :show
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    @book.update_attributes(params[:book])
    render :show
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end
  def new
    @ingredient = Ingredient.new
  end
  def create
    @ingredient = Ingredient.create(params[:ingredient])
    render :show
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update_attributes(params[:ingredient])
    render :show
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    recipe = Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.text_field :title, :autofocus => true %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :cuisine %>
  <%= f.label :cuisine %>
  <br>
  <%= f.text_field :chef %>
  <%= f.label :chef %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <% Recipe.order(:name).each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes), {class: "checkbox inline"} %>
  <% end %>
  <p><p>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Book', new_book_path) %>
  </li>
</ul>

<% @books.each do |book| %>
  <div class="row">
     <div class="span3 offset1">
      <p class="lead"><%= link_to(book.title, book) %></p>
      <p class="text-info"><%= book.cuisine %></p>
      <p class="text-warning"><%= book.chef %></p>
    </div>
    <div class="span8">
      <%= image_tag(book.image) %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Book', new_book_path) %></li>
  <li><%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure?') %></li>
  <li><%= link_to('Edit Book', edit_book_path(@book)) %></li>
</ul>


<div class="row">
     <div class="span3 offset1">
      <p class="lead"><%= link_to(@book.title, @book) %></p>
      <p class="text-info"><%= @book.cuisine %></p>
      <p class="text-info"><%= @book.chef %></p>
    </div>
    <div class="span8">
      <p class="text-warning"><%= image_tag(@book.image) %></p>
    </div>
</div>

<br>
<% @book.recipes.each do |recipe| %>
  <div class="row">
    <div class="span3 offset1">
      <p class="lead"><%= recipe.name %></p>
      <%= image_tag(recipe.image) %>
    </div>

    <div class="span8">
      <% recipe.ingredients.each do |ingredient| %>
        <%= ingredient.name %>
        <%= image_tag(ingredient.image,  size: "40x40") %>
      <% end %>
    </div>
   </div>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.text_field :name, :autofocus => true %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :measurement %>
  <%= f.label :measurement %>
  <br>
  <%= f.text_field :cost %>
  <%= f.label :cost %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <p><p>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<ul class="nav nav-pills">
  <li>
<%= link_to('New Ingredient', new_ingredient_path) %>
  </li>
</ul>

<table class="table .table-striped">
<% @ingredients.each do |ingredient| %>
  <tr>
    <td>
        <p class="lead"><%= link_to(ingredient.name, ingredient) %>
        <p><%= ingredient.measurement %>
        <p><%= number_to_currency ingredient.cost %>
      </td>
    <td>
      <%= image_tag(ingredient.image, size: "100x100") %>
    </td>
</tr>
<% end %>
</table>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Ingredient', new_ingredient_path) %></li>
  <li><%= link_to('Edit Ingredient', edit_ingredient_path(@ingredient)) %></li>
  <li><%= link_to('Delete Ingredient', @ingredient, :method => :delete, :confirm => 'Are you sure?') %></li>
</ul>

<div class="row">
  <div class="span3 offset1">
   <p class="lead"><%= @ingredient.name %>
   <p><%= @ingredient.measurement %>
   <p><%= number_to_currency @ingredient.cost %>
  </div>
  <div class="span8">
    <p class="text-warning"><%= image_tag(@ingredient.image) %></p>
  </div>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
          <li><h4>Le Cook Book App</h4></li>
        </ul>
        <ul class="nav pull-right">
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>


  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">

<%= render 'layouts/header' %>
<section>
  <div class="row-fluid">
    <div class="span2">
      <ul class="nav nav-tabs nav-stacked">
        <li><%= link_to('Books', books_path) %></li>
        <li><%= link_to('Recipes', recipes_path) %></li>
        <li><%= link_to('Ingredients', ingredients_path) %></li>
      </ul>
    </div>
    <div class="span10">
      <%flash.each do|key,value|%>
              <div class="alert alert-<%=key%>"> <%=value%> </div>
      <%end%>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= debug(session) if Rails.env.development? %>
  </div>
</section>

</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.text_field :name, :autofocus => true %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :course %>
  <%= f.label :course %>
  <br>
  <%= f.text_field :cooktime %>
  <%= f.label :cooktime %>
  <br>
  <%= f.text_field :servingsize %>
  <%= f.label :servingsize %>
  <br>
  <%= f.text_field :instructions %>
  <%= f.label :instructions %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <% Ingredient.order(:name).each do |ingredient| %>
    <span><%= ingredient.name %></span>
    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a), {class: "checkbox inline"} %>
  <% end %>
  <p><p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Recipe', new_recipe_path) %>
  </li>
</ul>


<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="span3 offset1">
      <p class="lead"><%= link_to(recipe.name, recipe) %>
      <p><%= recipe.course %>
      <p><%= recipe.cooktime %>
      <p><%= recipe.servingsize %><
      <p><%= recipe.instructions %>
    </div>
    <div class="span8">
      <p><%= image_tag(recipe.image) %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Recipe', new_recipe_path) %></li>
  <li><%= link_to('Edit Recipe', edit_recipe_path(@recipe)) %></li>
  <li><%= link_to('Delete Recipe', @recipe, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="span3 offset1">
    <p class="lead"><%= @recipe.name %></p>
    <div class="span8">
      <p class="text-warning"><%= image_tag(@recipe.image) %></p>
    </div>
  </div>
  <div class="span8">
    <% @recipe.ingredients.each do |ingredient| %>
      <p><%= ingredient.name %>
      <%= image_tag(ingredient.image,  size: "40x40") %></p>
    <% end %>
  </div>
</div>